name: 'Sync Project Files Action'
description: 'Detects changes in WORKLOG.md or PROJECT.md, processes them based on file-specific rules, and opens a PR.'

inputs:
  target_repo:
    description: 'The repository to create the pull request in (e.g., "owner/repo").'
    required: true
  target_branch:
    description: 'The base branch to create the pull request against.'
    required: false
    default: 'main'
  destination_path:
    description: 'The base folder path in the target repo (e.g., "portfolio-files").'
    required: false
    default: 'files'
  token:
    description: 'A Personal Access Token (PAT) with repo scope for the target repository.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Git
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Clone Target Repository
      shell: bash
      run: |
        git clone https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.target_repo }}.git target_repo_clone

    - name: Create Branch and Process Files
      shell: bash
      run: |
        cd target_repo_clone
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        
        # Create a single branch for this update
        BRANCH_NAME="update/${REPO_NAME}-${{ github.sha }}"
        git checkout -b $BRANCH_NAME
        echo "✅ Created new branch: $BRANCH_NAME"
        
        FILES_ADDED=0

        # --- RULE 1: PROCESS PROJECT.MD (OVERWRITE) ---
        if [ -f ../PROJECT.md ]; then
            echo "Processing PROJECT.md (overwrite mode)..."
            DEST_DIR="${{ inputs.destination_path }}/project"
            mkdir -p "$DEST_DIR"
            
            # The filename is now static, no suffix needed
            FINAL_FILENAME="$DEST_DIR/${REPO_NAME}-PROJECT.md"
            
            cp ../PROJECT.md "$FINAL_FILENAME"
            echo "Copied PROJECT.md to $FINAL_FILENAME"

            FILES_ADDED=1
        fi

        # --- RULE 2: PROCESS WORKLOG.MD (PARSE AND SPLIT) ---
        if [ -f ../WORKLOG.md ]; then
            echo "Processing WORKlOG.md (overwrite mode)..."
            DEST_DIR="${{ inputs.destination_path }}/worklog"
            mkdir -p "$DEST_DIR"
            
            # The filename is now static, no suffix needed
            FINAL_FILENAME="$DEST_DIR/${REPO_NAME}-WORKLOG.md"
            
            cp ../WORKLOG.md "$FINAL_FILENAME"
            echo "Copied WORKLOG.md to $FINAL_FILENAME"

            FILES_ADDED=1
        fi
        
        echo "FILES_ADDED=$FILES_ADDED" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Commit and Push Changes
      if: env.FILES_ADDED == '1'
      shell: bash
      run: |
        cd target_repo_clone
        git add .
        
        if ! git diff --staged --quiet; then
          echo "Content has changed. Committing and pushing..."
          git commit -m "feat(docs): Sync project files from ${{ github.repository }}"
          git push origin ${{ env.BRANCH_NAME }}
        else
          echo "No net content changes detected. Skipping commit and PR."
          # Set flag to 0 so the PR step is skipped
          echo "FILES_ADDED=0" >> $GITHUB_ENV
        fi

    - name: Create Pull Request
      if: env.FILES_ADDED == '1'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh pr create --repo ${{ inputs.target_repo }} \
           --title "Sync project files from ${{ github.repository }}" \
           --body "Automated PR to sync updated project documentation." \
           --base "${{ inputs.target_branch }}" \
           --head "${{ env.BRANCH_NAME }}"
        echo "✅ Pull request created."
