name: 'Sync Worklog on Change'

on:
  push:
    branches:
      - main
    paths:
      - 'WORKLOG.md'
      - 'PROJECT.md'

jobs:
  sync_worklog_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Call the Worklog Sync Action
        # Use the format 'owner/repo@ref'
        # 'ref' can be a branch name (e.g., @main) or a version tag (e.g., @v1)
        uses: EnzoReyes11/worklog-action@main 
        with:
          # The central repository where all worklogs are collected
          target_repo: 'EnzoReyes11/blog'

          # The folder within that repo to place the file
          destination_path: 'content' 

          # The token you stored in secrets
          token: ${{ secrets.WORKLOG_ACTION_PAT }}
